# Generated by Django 6.0.5 on 2026-05-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Lahore', max_length=50)),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
