# Generated by Django 5.2.8 on 2026-05-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('area_marla', models.DecimalField(decimal_places=2, help_text='Area in Marlas', max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, help_text='Sale Price', max_digits=15)),
                ('property_status', models.CharField(choices=[('available', 'Available'), ('rent', 'For Rent'), ('sold', 'Sold')], default='available', max_length=10)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rent (if applicable)', max_digits=12, null=True)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('kitchens', models.IntegerField(default=1)),
                ('construction_year', models.IntegerField(blank=True, null=True)),
                ('number_of_floors', models.IntegerField(default=1)),
                ('servant_rooms', models.IntegerField(default=0)),
                ('store_rooms', models.IntegerField(default=0)),
                ('current_per_marla_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('has_lawn', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_servant_quarter', models.BooleanField(default=False)),
                ('has_study_room', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField(default=False)),
                ('has_dining_room', models.BooleanField(default=False)),
                ('has_living_room', models.BooleanField(default=False)),
                ('has_electricity_backup', models.BooleanField(default=False)),
                ('is_corner_plot', models.BooleanField(default=False)),
                ('is_facing_park', models.BooleanField(default=False)),
                ('custom_features', models.TextField(blank=True, help_text='Comma-separated custom features', null=True)),
                ('description', models.TextField()),
                ('admin_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='listings.location')),
            ],
            options={
                'db_table': 'listing',
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(max_length=500, upload_to='property_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(db_column='listing_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'db_table': 'listing_image',
            },
        ),
    ]
