# Generated by Django 5.2.8 on 2026-06-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_options_listing_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('plot', 'Plot'), ('rent', 'Rent')], default='house', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=10),
        ),
    ]
