# Generated by Django 5.2.8 on 2026-06-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_property_type_alter_listing_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='buyer_name',
            field=models.CharField(blank=True, help_text="Buyer's name (required when property status is 'sold')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='expected_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected profit/revenue from this deal (cannot exceed property price)', max_digits=15, null=True),
        ),
    ]
