# Generated by Django 6.0.5 on 2026-05-23 06:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRate',
            fields=[
                ('location_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100, unique=True)),
                ('area_name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Lahore', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'location_rate',
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalYearRate',
            fields=[
                ('year_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('price_5_marla', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('1000000000.00'))])),
                ('price_10_marla', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('1000000000.00'))])),
                ('price_1_kanal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('1000000000.00'))])),
                ('price_2_kanal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('1000000000.00'))])),
                ('per_marla_rate_5', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('per_marla_rate_10', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('per_marla_rate_1k', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('per_marla_rate_2k', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('growth_percentage_5', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('growth_percentage_10', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('growth_percentage_1k', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('growth_percentage_2k', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(db_column='location_rate_id', on_delete=django.db.models.deletion.CASCADE, related_name='years', to='historical_rates.locationrate')),
            ],
            options={
                'db_table': 'historical_year_rate',
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['location', 'year'], name='historical__locatio_b8f262_idx'), models.Index(fields=['year'], name='historical__year_111e49_idx')],
                'unique_together': {('location', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistoryLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('location_added', 'Location Added'), ('location_updated', 'Location Updated'), ('location_deleted', 'Location Deleted'), ('year_added', 'Year Added'), ('year_updated', 'Year Updated'), ('year_deleted', 'Year Deleted'), ('price_updated', 'Price Updated'), ('bulk_update', 'Bulk Update'), ('data_import', 'Data Import'), ('data_export', 'Data Export')], default='price_updated', max_length=50)),
                ('field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(db_column='location_rate_id', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='historical_rates.locationrate')),
            ],
            options={
                'db_table': 'price_history_log',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['location', '-changed_at'], name='price_histo_locatio_9bcb10_idx'), models.Index(fields=['changed_at'], name='price_histo_changed_49abab_idx'), models.Index(fields=['action'], name='price_histo_action_ee9c3f_idx')],
            },
        ),
    ]
