# Generated by Django 6.0.5 on 2026-05-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_full_name_user_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
    ]
