# Generated by Django 6.0.5 on 2026-05-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_admin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
    ]
